### ISSUE TITLE
Error en la entrada de descripción

### ISSUE THREAD

**Issue by alvaroolt** [Javierfs94/PGNParejas#10]
https://github.com/Javierfs94/PGNParejas/blob/70aafa542f230aa45f198e3f585a9e5b36bc0433/gestisimal/TestGestisimal.java#L81
Estaba probando cómo funcionaba vuestro TestGestisimal, y me he dado cuenta de que a la hora de modificar un artículo, no permite introducir una descripción, pasa a la siguiente entrada de teclado.

**Comment by Javierfs94** [comment]
Ya lo sabemos :)
